apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: proxy-monitoring
data:
  grafana.ini: |
    [analytics]
    check_for_updates = true
    
    [grafana_net]
    url = https://grafana.net
    
    [log]
    mode = console
    level = info
    
    [paths]
    data = /var/lib/grafana/
    logs = /var/log/grafana
    plugins = /var/lib/grafana/plugins
    provisioning = /etc/grafana/provisioning
    
    [server]
    protocol = http
    http_addr = 0.0.0.0
    http_port = 3000
    domain = localhost
    enforce_domain = false
    root_url = %(protocol)s://%(domain)s:%(http_port)s/
    router_logging = false
    static_root_path = public
    enable_gzip = false
    cert_file =
    cert_key =
    socket =
    
    [database]
    type = sqlite3
    host = 127.0.0.1:3306
    name = grafana
    user = root
    password =
    url =
    ssl_mode = disable
    path = grafana.db
    max_idle_conn = 2
    max_open_conn =
    
    [users]
    allow_sign_up = false
    allow_org_create = false
    auto_assign_org = true
    auto_assign_org_role = Viewer
    login_hint = email or username
    default_theme = dark
    
    [auth.anonymous]
    enabled = false
    
    [auth.github]
    enabled = false
    
    [auth.basic]
    enabled = true
    
    [auth.ldap]
    enabled = false
    
    [smtp]
    enabled = false
    
    [emails]
    welcome_email_on_sign_up = false
    
    [alerting]
    enabled = true
    execute_alerts = true
    
    [metrics]
    enabled = true
    interval_seconds = 10
    
    [metrics.graphite]
    address =
    prefix = prod.grafana.%(instance_name)s.
    
    [snapshots]
    external_enabled = true
    external_snapshot_url = https://snapshots-origin.raintank.io
    external_snapshot_name = Publish to snapshot.raintank.io
    snapshot_remove_expired = true
    snapshot_TTL_days = 90
    
    [dashboards.json]
    enabled = true
    path = /var/lib/grafana/dashboards
    
    [security]
    admin_user = admin
    admin_password = admin
    secret_key = SW2YcwTIb9zpOOhoPsMm
    login_remember_days = 7
    cookie_username = grafana_user
    cookie_remember_name = grafana_remember
    disable_gravatar = false
    data_source_proxy_whitelist =

  datasources.yml: |
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      orgId: 1
      url: http://prometheus:9090
      basicAuth: false
      isDefault: true
      version: 1
      editable: false
      jsonData:
        httpMethod: POST
        queryTimeout: 60s
        timeInterval: 15s
    - name: Prometheus-Alertmanager
      type: prometheus  
      access: proxy
      orgId: 1
      url: http://alertmanager:9093
      basicAuth: false
      isDefault: false
      version: 1
      editable: false

  dashboardproviders.yml: |
    apiVersion: 1
    providers:
    - name: 'Proxy Monitoring'
      orgId: 1
      folder: 'Proxy Monitoring'
      folderUid: proxy_monitoring
      type: file
      disableDeletion: false
      editable: true
      allowUiUpdates: true
      options:
        path: /var/lib/grafana/dashboards/proxy-monitoring
    - name: 'Infrastructure'
      orgId: 1
      folder: 'Infrastructure'
      folderUid: infrastructure
      type: file
      disableDeletion: false
      editable: true
      allowUiUpdates: true
      options:
        path: /var/lib/grafana/dashboards/infrastructure
    - name: 'Istio Service Mesh'
      orgId: 1
      folder: 'Istio'
      folderUid: istio_mesh
      type: file
      disableDeletion: false
      editable: true
      allowUiUpdates: true
      options:
        path: /var/lib/grafana/dashboards/istio